// Generated by CoffeeScript 1.6.2
(function() {
  var myModule;

  myModule = angular.module('myModule', [], function($provide) {
    return $provide.factory('notify', [
      '$window', function(win) {
        var msgs;

        msgs = [];
        return function(msg) {
          msgs.push(msg);
          if (msgs.length === 3) {
            win.alert(msgs.join("\n"));
            return msgs = [];
          }
        };
      }
    ]);
  });

  myModule.controller('ModalCtrl', [
    '$scope', function($scope) {
      return $scope.page_title = 'Triunfo';
    }
  ]);

}).call(this);
