// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = angular.module('app', ['ui.keypress'], function($provide) {
    return $provide.factory('notify', [
      '$window', function(win) {
        var msgs;

        msgs = [];
        return function(msg) {
          msgs.push(msg);
          if (msgs.length === 3) {
            win.alert(msgs.join("\n"));
            return msgs = [];
          }
        };
      }
    ]);
  });

  app.controller('ModalCtrl', [
    '$scope', function($scope) {
      $scope.page_title = 'el titulo';
      return $scope.keypressCallback = function($event) {
        alert('Voila!');
        return $event.preventDefault();
      };
    }
  ]);

}).call(this);
