// Generated by CoffeeScript 1.6.2
(function() {
  var notifyCtrl, notifyModule;

  notifyModule = angular.module('notifyModule', []);

  notifyModule.run(function($templateCache, $http) {
    var modalHtml;

    modalHtml = $http.get('views/directives/modal.html');
    return $templateCache.put('modal.html', modalHtml);
  });

  notifyModule.factory('notify', [
    '$window', function(win) {
      var msgs;

      msgs = [];
      return function(msg) {
        return win.alert(msg);
      };
    }
  ]);

  notifyCtrl = function(scope, notifyService) {
    scope.animals = [
      {
        name: 'giraffe'
      }, {
        name: 'elephant'
      }, {
        name: 'monkey'
      }
    ];
    return scope.callNotify = function(msg) {
      return notifyService(msg);
    };
  };

  notifyCtrl.$inject = ['$scope', 'notify'];

  notifyModule.controller('notifyCtrl', notifyCtrl);

}).call(this);
